server {
    listen 80;
    listen [::]:80;

    root /var/www/yourvichandirectoryname/somechan-5.1.4;
    index index.html;
    server_name somechan.example.net;
 
	location /ua_debug.log {
		return 403;
	}
 
    location / {
        try_files $uri $uri/ =404;
    }
 
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
    }
}